<<<<<<< HEAD
name: Work 1 Oscar
on: [push]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Print Something
        run: echo "Hola pitaya"
=======
name: Work 1 sergio
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Print Something
          run: echo "Hola papu"
>>>>>>> b1d391f07932077f9774cbfa2d4799bb072a2eb0
